/**
 * ARCHITECT-EYE OS: SOVEREIGN OPERATIONAL ENGINE (v6.1 - PRODUCTION)
 * -------------------------------------------------------------------------
 * Updates: Backend-driven synchronization, real-time signal parsing,
 * and autonomous hive-mind state orchestration.
 */

let systemStatus = { state: 'SYNCING...', lastSync: 'N/A' };
const agentAssets = ["nx.jpg", "ny.jpg", "nz.jpg", "px.jpg", "py.jpg", "pz.jpg", "nx.jpg", "ny.jpg", "nz.jpg", "px.jpg", "py.jpg", "pz.jpg"];

/**
 * Syncs the frontend state with the status.txt file generated by 
 * the Sovereign Execution Engine (GitHub Action).
 */
async function syncSystemStatus() {
    try {
        // Fetching the current integrity signal from the root status file
        const response = await fetch('status.txt?nocache=' + new Date().getTime());
        const rawData = await response.text();
        
        // Parsing the operational state from the signal
        const isOperational = /Engine-Operational/i.test(rawData);
        systemStatus.state = isOperational ? 'OPERATIONAL' : 'CRITICAL';
        systemStatus.lastSync = new Date().toLocaleTimeString();
        
        updateUI();
    } catch (e) {
        // Fallback state if the bridge connection is severed
        systemStatus.state = 'OFFLINE';
        updateUI();
    }
}

/**
 * Updates the UI elements based on the parsed backend state.
 */
function updateUI() {
    const statusFeed = document.getElementById('status-feed');
    if (statusFeed) {
        statusFeed.innerText = `CORE: ${systemStatus.state} | LAST SYNC: ${systemStatus.lastSync}`;
        statusFeed.style.color = systemStatus.state === 'OPERATIONAL' ? '#00d4ff' : '#ff0033';
    }
    
    // Updates node borders to reflect real-time threat levels
    document.querySelectorAll('.agent-node').forEach(node => {
        node.style.borderColor = systemStatus.state === 'OPERATIONAL' ? '#00d4ff' : '#ff0033';
    });
}

/**
 * Activates individual autonomous agents with state-dependent tasks.
 */
function activateAgent(index) {
    const nodes = document.querySelectorAll('.agent-node');
    const node = nodes[index];
    if (!node) return;

    setInterval(() => {
        // Tasks adapt based on the operational state of the Rust backend
        const taskTypes = systemStatus.state === 'OPERATIONAL' 
            ? ["ENCRYPTING", "SYNCING", "VERIFYING", "SCANNING", "COMPUTING"]
            : ["DEFENSE_PROTOCOL", "ISOLATING_CORE", "REPAIRING"];
            
        const currentTask = taskTypes[Math.floor(Math.random() * taskTypes.length)];
        // Generating a unique hash ID based on the last sync timestamp
        const liveId = btoa(systemStatus.lastSync + index).substring(0, 8).toUpperCase();
        
        node.innerHTML = `
            <img src="space/${agentAssets[index]}" style="width:40px; height:40px; border-radius:50%; margin-bottom:5px;">
            <br><strong>AGENT-${index}</strong>
            <br><span>${currentTask}...</span>
            <br><small>ID:${liveId}==</small>
        `;
    }, 4000); 
}

// System initialization and heartbeat
document.addEventListener('DOMContentLoaded', () => {
    initHiveMind(); // Rendering initial agent grid
    syncSystemStatus(); // First synchronization pulse
    
    for (let i = 0; i < 12; i++) {
        activateAgent(i);
    }
    
    // Periodic synchronization heartbeat (3-second interval)
    setInterval(syncSystemStatus, 3000);
});
